services:
  web:
    build:
      context: ../django_culture
      dockerfile: ./Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 8000:80
    depends_on:
      - web
  redis:
    image: redis
    command: redis-server --requirepass random_password
    ports:
      - 6379

  celery:
    build:
      context: ../django_culture
      dockerfile: ./Dockerfile.prod
    command: celery -A core worker -l INFO
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - db

  flower:
    build:
      context: ../django_culture
      dockerfile: ./Dockerfile.prod
    command: celery -A core flower --broker=redis://random_password@redis:6379/0
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    ports:
      - 5555:5555
    depends_on:
      - web
      - celery
      - db
      - redis


volumes:
  postgres_data:
  static_volume:
  media_volume:
